version: '2'
services:
    coprodepa-app:
        image: coprodepa
        external_links:
            - coprodepa-mysql:mysql
            - coprodepa-elasticsearch:elasticsearch
        environment:
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:mysql://mysql:3306/coprodepa?useUnicode=true&characterEncoding=utf8&useSSL=false
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
            - SPRING_DATA_ELASTICSEARCH_CLUSTER_NODES=elasticsearch:9300
        ports:
            - 8080:8080
    coprodepa-mysql:
        extends:
            file: mysql.yml
            service: coprodepa-mysql
    coprodepa-elasticsearch:
        extends:
            file: elasticsearch.yml
            service: coprodepa-elasticsearch
